Fix: "ФЗ-9"
Kompas13/java-filmorate pull request #2
Opened 2023-05-11 10:28 UTC by Kompas13

1.0

2023-05-12 15:26 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .name("����������")
В гитхабе явно поехала кодировка, поэтому нужно либо починить UTF-8 для русского языка, либо писать на английском)

2023-05-12 15:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
1) Для getReleaseDate тоже имеет смысл добавить проверку на null

2) дату лучше сделать константой

2023-05-12 15:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Количество добавленных фильмов: {}", films.size());
Лучше уровень лога поднять до info, потому что это информация полезна и для мониторинга, не только при разработке

2023-05-12 15:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        films.put(film.getId(), film);
Добавь еще проверку на дату релиза, и следующий вариант - все проверки можно вынести в метод вроде void validate(Film film), и использовать его в post и put

2023-05-12 15:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        films.put(film.getId(), film);
Не увидел проверки условия "максимальная длина описания — 200 символов"

2023-05-12 15:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new UserAlreadyExistException("Пользователь с электронной почтой " +
Ты сделал так много исключений, но на самом деле они скорее об одном - о валидации данных, поэтому я бы рекомендовал лучше сделать одно ValidationException, в подробности добавить в сообщение исключения.

2023-05-12 15:26 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(min = 1, max = 200)
Писал замечание насчет проверки длины - все, вижу, как работает валидация

2023-05-12 15:26 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(0, userController.getUsers().size(), "����� ������������� ������ ���� 0");
А что проверяет этот метод? ты ведь и не добавлял юзера в контроллер

2023-05-15 06:52 UTC, Kompas13 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .name("����������")
Поменял на английский

2023-05-15 06:56 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Проверка на null добавлена в класс File.
Константа добавлена.

2023-05-15 06:58 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Количество добавленных фильмов: {}", films.size());
Все логи изменены на info

2023-05-15 07:06 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        films.put(film.getId(), film);
Все проверки (кроме проверки на некорректный ID в put, т.к. она используется только в нем) вынесены в отдельный метод void validate(Film film)

2023-05-15 07:06 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        films.put(film.getId(), film);
Film.class

2023-05-15 07:21 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new UserAlreadyExistException("Пользователь с электронной почтой " +
ИСправлено.

2023-05-15 07:23 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(min = 1, max = 200)
:)

2023-05-15 09:12 UTC, Kompas13 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(0, userController.getUsers().size(), "����� ������������� ������ ���� 0");
Поправил тесты.

2023-05-16 06:42 UTC, Yang-Pi requested changes

2023-05-16 06:42 UTC, Yang-Pi commented on .gitignore
> -*.class
Файл .gitignore не нужно менять, изменяй только бизнес-логику программы

2023-05-16 06:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
Не хватает вызова нового метода validate

2023-05-16 06:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank()) {
Для этого класса тоже актуально - вынести проверки в метод, чтобы не дублировать код.

2023-05-16 06:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(user.getId(), user);
Не хватает проверки даты рождения

2023-05-16 07:21 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(user.getId(), user);
Проверка даты рождения в классе User - аннотация @PastOrPresent

2023-05-16 07:21 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank()) {
Добавил

2023-05-16 07:21 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
Косяк, поправил.

2023-05-16 07:21 UTC, Kompas13 commented on .gitignore
> -*.class
Я его вроде и не менял), на всякий случай вернул ту версию которая была до изменений в гите.

2023-05-16 15:21 UTC, Yang-Pi approved these changes

2023-05-16 15:21 UTC, Yang-Pi commented on .gitignore
В этом файле есть изменения, а их быть не должно, поэтому верни, пожалуйста, исходную версию. Это важно, потому что в дальнейшем это могут быть проблемы с прохождением авто-тестов

2023-05-16 15:21 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(user.getId(), user);
Точно

2023-05-23 11:35 UTC, merged