Fix: "ФЗ-10 1 итерация 1.1"
Kompas13/java-filmorate pull request #3
Opened 2023-05-26 13:09 UTC by Kompas13

2023-05-27 10:55 UTC, Yang-Pi requested changes

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Builder.Default
Когда для поля ставится эта аннотация, то нужно еще прописать значение, которым поле будет проинициализовано, а иначе по умолчанию будет 0. Это ожидаемое поведение?

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
Не хватает еще логирования сообщения об ошибке, чтобы на стороне сервиса тоже была эта информация для мониторинга.

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Имеет смысл добавить хэндлер и для ошибок типа Throwable - те все исключения, и присвоить статус-код 500.

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        //log.info("Popular films are returned: {}", popular);
Не оставляй закомментированный код в репозитории

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users;
Возвращай копию, а не оригинал списка

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new ValidationException("Указанный ID не найден" + userId);
Мб добавить еще один тип исключения, чтобы использовать статус NOT_FOUND для таких ситуаций, а не BAD_REQUEST

2023-05-27 10:55 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
В качестве рекомендации: классы-хранилища очень схожи по своей структуре, поэтому имеет смысл ввести некий интерфейс-дженерик для них. Это будет особенно актуально, когда появится и другие типы хранилища.

2023-05-29 07:52 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Добавлен.

2023-05-29 07:52 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        //log.info("Popular films are returned: {}", popular);
Убрал.

2023-05-29 08:00 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @Builder.Default
Добавил дополнительно аннотацию @NotNull(message = "Не задана продолжительность фильма.")

2023-05-29 09:23 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
Добавил лог.

2023-05-29 09:26 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users;
Исправил.

2023-05-29 11:36 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new ValidationException("Указанный ID не найден" + userId);
Добавил

2023-05-29 11:41 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Я честно говоря не совсем понял что нужно сделать(. Сейчас обращение к InMemoryFilmStorage идет через интерфейс FilmStorage, а к InMemoryUserStorage через интерфейс UserStorage (так по ТЗ), Мне нужно заменить интерфейсы FilmStorage и UserStorage на интерфейс дженерик (например Storage) или как-то по другому?

2023-05-29 20:44 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Да, ты все верно понял. То есть в качестве параметра <T> будет передаваться User или Film, а не отдельный интерфейс хранилища под каждый тип.

2023-05-29 20:57 UTC, Yang-Pi requested changes

2023-05-29 20:57 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("Данные не найдены ");
Я бы рассматривал ValidationException скорее как статус-код 400, тк это проблема в переданных данных, а не в наличии записи.

2023-05-29 20:57 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
На самом деле это исключение по своей смысловой нагрузке повторяет validation exception, поэтому мб его даже и не нужно добавлять.

2023-05-29 20:57 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmId < 1 || userId < 1) {
Подобные валидации у тебя реализованы в рамках хранилища, поэтому не стоит их писать и в сервисе, и в хранилище.

2023-05-29 20:57 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmId < 1 || userId < 1) {
Но для юзера никаких проверок сейчас нет

2023-05-29 20:57 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getFilmById(filmId).getLikesUser().add(userId);
А что если getLikesUser вернет копию коллекции? Чтобы для ответа на этот вопрос не приходилось идти в класс модели, то лучше просто сделать метод - addLike.

2023-05-30 19:19 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getFilmById(filmId).getLikesUser().add(userId);
Добавил методы.

2023-05-31 07:41 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Сделал

2023-05-31 07:58 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("Данные не найдены ");
Исправил.

2023-05-31 07:59 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Удалил, оставил 3 исключения.

2023-05-31 08:04 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmId < 1 || userId < 1) {
Эти методы у меня реализованы только в пакете Service в соответствии с ТЗ, лишние проверки убрал, добавил только проверку для User (наличие User в мапе users)
По ТЗ:
Создайте UserService, который будет отвечать за такие операции с пользователями, как добавление в друзья, удаление из друзей, вывод списка общих друзей...
Создайте FilmService, который будет отвечать за операции с фильмами, — добавление и удаление лайка, вывод 10 наиболее популярных фильмов по количеству лайков...

2023-05-31 20:45 UTC, Yang-Pi approved these changes

2023-05-31 20:45 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    void validateFilm(Film film) {
Старайся соблюдать порядок методов - сначала идут все публичные, которые фактически описывают то, как с объектом класса можно взаимодействовать, а уже потом по мере понижения видимости.

2023-06-15 11:58 UTC, merged