Fix: "ФЗ-11 1 итерация 1.1"
Kompas13/java-filmorate pull request #4
Opened 2023-06-22 11:29 UTC by Kompas13

2023-06-23 12:19 UTC, Yang-Pi requested changes

2023-06-23 12:19 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.genreStorage = new GenreStorage(jdbcTemplate);
Это хранилище нужно получать в качестве аргумента конструктора.

2023-06-23 12:19 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendStorage.java
> +public class FriendStorage {
В названии хранилищ, работающих с бд, следуй тому же паттерну, что и для фильмов с пользователями, те Db нужно добавить

2023-06-23 12:19 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Сервис для жанра можно сделать частью сервиса фильмов, потому что может понадобиться такой вариант взаимодействия, когда понадобятся оба хранилища. В этом случае логику удобнее описывать и поддерживать в рамках одного класса.

2023-06-23 13:13 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        this.genreStorage = new GenreStorage(jdbcTemplate);
Поправил.

2023-06-23 13:14 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendStorage.java
> +public class FriendStorage {
Исправил.

2023-06-23 13:14 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
GenreService убрал, перенес методы в filmService.

2023-06-24 18:26 UTC, Yang-Pi approved these changes

2023-06-24 18:30 UTC, Yang-Pi requested changes

2023-06-24 18:30 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Genre> findAll() {
Не самое удачное название, найти все - что именно? Найти все жанры нужно.

2023-06-24 18:30 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Методы ты перенес, но сервис жанров все еще существует.

2023-06-24 18:30 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/RatingService.java
> +public class RatingService {
Разумно также и сервис рейтинга тоже перетащить в сервис фильмов, только пострайся выбрать один паттерн для названий для этих методов (один паттерн я имею в виду со схожими методами для жанров), чтобы не было двусмысленности, что мтеоды делают.

2023-06-24 19:01 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Забыл удалить(

2023-06-24 19:06 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Genre> findAll() {
Поправил

2023-06-24 19:15 UTC, Kompas13 commented on src/main/java/ru/yandex/practicum/filmorate/service/RatingService.java
> +public class RatingService {
Сделал.

2023-06-24 19:23 UTC, Yang-Pi approved these changes

2023-07-01 17:33 UTC, merged